# Generated by Django 5.1 on 2024-08-31 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField()),
                ('id_pk', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('id_pk', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=256)),
                ('id_pk', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerText', models.CharField()),
                ('isCorrect', models.BooleanField()),
                ('id_pk', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizziz.questions')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='quizId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizziz.quizzes'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=28, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('id_pk', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizziz.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pk', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('score', models.IntegerField()),
                ('takenAt', models.DateTimeField(auto_now_add=True)),
                ('quizId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizziz.quizzes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizziz.users')),
            ],
        ),
    ]
