# Generated by Django 5.1 on 2024-08-31 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizziz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id_pk',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
