# Generated by Django 5.1 on 2024-08-31 11:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizziz', '0002_alter_users_id_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id_pk',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='id_pk',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='id_pk',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='id_pk',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='roles',
            name='id_pk',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
